name: daily
on:
  schedule:
    # Run load testing at 01:30 UTC every day
    - cron: '30 1 * * *'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          SCRIPT="${GITHUB_WORKSPACE}/src/test/scrips/test-repetition.sh"
          # Make script runnable
          chmod +x "${GITHUB_WORKSPACE}src/test/scrips/test-repetition.sh"
          # Test eo-parser
          bash "${SCRIPT} --max 10 --folder ${GITHUB_WORKSPACE}/eo-parser"
          # Test eo-maven-plugin
          bash "${SCRIPT} --max 10 --folder ${GITHUB_WORKSPACE}/eo-maven-plugin"
          # Test eo-runtime
          bash "${SCRIPT} --max 10 --folder ${GITHUB_WORKSPACE}/eo-runtime"
      # @todo #2085:90min Add GitHub action step to create an issue.
      #  It would be convenient to add github action step that will create an
      #  issue in case of any of the tests is failed. We can do it through
      #  <a href="https://github.com/JasonEtco/create-an-issue">create-an-issue</a>
      #  action. Also, you can read about that problem in that discussion:
      #  <a href="https://github.com/orgs/community/discussions/25111">
      #  Create an issue case the workflow fails</a>

